const items=[
['Faire des pancakes','Cuisine','🥞','15 min','Facile'],['Faire un puzzle','Jeux','🧩','30 min','Facile'],['Regarder un film','Culture','🍿','2 h','Facile'],['Faire une balade','Extérieur','🌳','45 min','Facile'],['Préparer des cookies','Cuisine','🍪','30 min','Facile'],['Faire un dessin','Créativité','🎨','20 min','Facile'],['Faire du sport','Sport & Bien-être','🏋️','20 min','Moyen'],['Lire un livre','Culture','📚','30 min','Facile'],['Faire un bricolage','Créativité','🛠️','45 min','Moyen'],['Jouer à un jeu de société','Jeux','🎲','1 h','Facile'],['Cuisiner une pizza','Cuisine','🍕','45 min','Facile'],['Faire du yoga','Sport & Bien-être','🧘','20 min','Facile']];
const cats=[['Jeux','🎮','Joue et amuse-toi','blue'],['Défis','💡','Teste tes limites','green'],['Cuisine','👨‍🍳','Régale-toi','orange'],['Créativité','🎨','Laisse parler ton imagination','purple'],['Sport & Bien-être','🏋️','Prends soin de toi','pink'],['Culture','📚','Apprends et découvre','cyan']];
const colors={Cuisine:'orange','Jeux':'blue','Culture':'cyan','Extérieur':'green','Créativité':'purple','Sport & Bien-être':'pink'};
const track=document.querySelector('#track'), result=document.querySelector('#result');
function card(x,small=false){return `<article class="r-card ${small?'small':''} ${colors[x[1]]||''}"><div class="pic">${x[2]}</div><div><b>${x[0]}</b><small>${x[1]} · ${x[3]}</small></div></article>`}
function buildTrack(){let arr=[];for(let i=0;i<5;i++)arr.push(...items);track.innerHTML=arr.map(x=>card(x)).join('')}
buildTrack();
const categories=document.querySelector('#categories');categories.innerHTML=cats.map(c=>`<button class="cat ${c[3]}"><span>${c[1]}</span><div><b>${c[0]}</b><small>${c[2]}</small></div><i>›</i></button>`).join('');
const ideas=document.querySelector('#ideas');ideas.innerHTML=items.slice(0,6).map(x=>`<article class="idea"><div class="idea-pic ${colors[x[1]]||''}">${x[2]}</div><div><b>${x[0]}</b><small>${x[1]} · ${x[3]} · ${x[4]}</small></div><span>›</span></article>`).join('');
let spinning=false;
function spin(){if(spinning)return;spinning=true;result.classList.add('hidden');const winner=items[Math.floor(Math.random()*items.length)];const index=items.indexOf(winner)+items.length*3+Math.floor(Math.random()*3);const cardH=96;track.style.transition='none';track.style.transform='translateY(0)';requestAnimationFrame(()=>{requestAnimationFrame(()=>{track.style.transition='transform 4.2s cubic-bezier(.12,.78,.12,1)';track.style.transform=`translateY(${-index*cardH+140}px)`})});setTimeout(()=>{result.innerHTML=`<div class="winner-pic ${colors[winner[1]]||''}">${winner[2]}</div><div><small>🎯 C’est parti !</small><h3>${winner[0]}</h3><p>${winner[1]} · ${winner[3]} · ${winner[4]}</p></div><button onclick="spin()">🔄</button>`;result.classList.remove('hidden');spinning=false},4400)}
document.querySelector('#spin').onclick=spin;document.querySelector('#surprise').onclick=spin;
document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();ideas.innerHTML=items.filter(x=>x.join(' ').toLowerCase().includes(q)).map(x=>`<article class="idea"><div class="idea-pic ${colors[x[1]]||''}">${x[2]}</div><div><b>${x[0]}</b><small>${x[1]} · ${x[3]} · ${x[4]}</small></div><span>›</span></article>`).join('')||'<p class="empty">Aucune idée trouvée 😕</p>'});
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
